### ISSUE TITLE
Need help on developing annex identifier template for module documents

### ISSUE THREAD

**Issue by manuelfuenmayor** [metanorma/iso-10303-templates#17]
I'm really struggling to develop the [annex identifier template](https://github.com/metanorma/iso-10303-templates/blob/main/modules/module_annex_identifier.adoc) for module documents for these reasons:

* Unlike resource docs, there is no `schemas.yaml` file from where to take the path of the `.exp` files via:
```adoc
[lutaml_express, schemas, context]
----
...
----
```
* As a workaround, I can extract the schema name from `express-g-diagrams-arm.yaml` file and then build the `.exp` paths. But that would need to embed a `lutaml_express` block inside a `yaml2text` block. And that is not currently supported.
```adoc
[yaml2text,express-g-diagrams-arm.yaml,context]
----
...

// Extract the arm, mim, arm_lf, mim_lf paths, by using Liquid filters
{% assign arm_path = schema_name  | filters... %}

// This is not supported
[lutaml_express,{{ arm_path }},data]
--
// Build schema identifications
--

----

```

**Comment by TRThurman** [comment]
@manuelfuenmayor, all the relevant files are directly in the <module_name> directory.
here is a tree view of annotated_3d_model_data_quality_criteria :
.
├── arm.exp
├── arm.xml
├── arm_descriptions.xml
├── armexpg1.gif
├── armexpg1.xml
├── armexpg2.gif
├── armexpg2.xml
├── armexpg3.gif
├── armexpg3.xml
├── dvlp
│   ├── issues.xml
│   └── projmg.xml
├── fig-01.gif
├── index.xml
├── mim.exp
├── mim.xml
├── mim_concatenated.exp
├── mim_descriptions.xml
├── mimexpg1.gif
├── mimexpg1.xml
├── mimexpg2.gif
├── mimexpg2.xml
├── module.xml
├── nav
│   ├── arm_descriptions.xml
│   ├── arm_long_form.xml
│   ├── developer.xml
│   ├── issues_dvlp.xml
│   ├── mapping_view.xml
│   ├── mapping_view_with_test.xml
│   ├── mim_descriptions.xml
│   ├── module_index.xml
│   ├── select_matrix_view.xml
│   ├── select_view.xml
│   └── summary.xml
└── sys
    ├── 1_scope.xml
    ├── 2_refs.xml
    ├── 3_defs.xml
    ├── 4_info_reqs.xml
    ├── 5_main.xml
    ├── 5_mapping.xml
    ├── 5_mim.xml
    ├── 6_refdata.xml
    ├── a_short_names.xml
    ├── abstract.xml
    ├── b_obj_reg.xml
    ├── biblio.xml
    ├── c_arm_expg.xml
    ├── contents.xml
    ├── cover.xml
    ├── d_mim_expg.xml
    ├── e_exp.xml
    ├── e_exp_arm.xml
    ├── e_exp_arm_lf.xml
    ├── e_exp_mim.xml
    ├── e_exp_mim_lf.xml
    ├── f_guide.xml
    ├── foreword.xml
    ├── g_change.xml
    ├── introduction.xml
    ├── isocover.xml
    ├── main.xml
    ├── modindex.xml
    └── p28xsd.xml

**Comment by ronaldtse** [comment]
@manuelfuenmayor i will be pushing the schema.yaml files shortly.

**Comment by ronaldtse** [comment]
@manuelfuenmayor do you not see this?

```sh
$ cat documents/iso-10303-1051/schemas.yaml
---
schemas:
  Geometric_tolerance_arm:
    path: ../../schemas/modules/geometric_tolerance/arm.exp
  Geometric_tolerance_mim:
    path: ../../schemas/modules/geometric_tolerance/mim.exp
```

**Comment by manuelfuenmayor** [comment]
@ronaldtse yes, that document has a `schemas.yaml`.

**Comment by ronaldtse** [comment]
This is done. Closing.
