### ISSUE TITLE
Module documents: missing mapping specification content (Clause 5.1)

### ISSUE THREAD

**Issue by kwkwan** [metanorma/iso-10303-templates#22]
The content in `mapping.yaml` is not included in the output.

**Comment by ronaldtse** [comment]
I believe @manuelfuenmayor is currently working on this.

**Comment by manuelfuenmayor** [comment]
> The content in mapping.yaml is not included in the output.

Yes, it is: https://github.com/metanorma/iso-10303-templates/blob/main/modules/_module_mappings.liquid#L174-L231

This from main branch.

@kwkwan which document doesn't show the mapping specification content?

**Comment by ronaldtse** [comment]
@manuelfuenmayor : @kwkwan was referring to ISO 10303-1064 (from https://github.com/metanorma/iso-10303-srl/issues/208). Can you check that? Thanks.

**Comment by ronaldtse** [comment]
@manuelfuenmayor I'm actually getting these errors when compiling this document:

```
No label has been processed for ID change_history
No label has been processed for ID arm
No label has been processed for ID mapping
No label has been processed for ID mim_express
No label has been processed for ID AnnexD
No label has been processed for ID annex_listings
```

**Comment by ronaldtse** [comment]
Ahh this is because the module schemas are not in schemas_all.yaml yet. I need to figure out how to fix this.

**Comment by manuelfuenmayor** [comment]
Ok, I'm checking...

**Comment by ronaldtse** [comment]
But there are still these:
```
No label has been processed for ID change_history
No label has been processed for ID AnnexD
No label has been processed for ID annex_listings
```

**Comment by ronaldtse** [comment]
<img width="546" alt="Screenshot 2024-05-09 at 3 03 38 AM" src="https://github.com/metanorma/iso-10303-templates/assets/11865/8f3115f2-b2c2-4304-9b6a-5aad5c88716c">

@manuelfuenmayor I can see the content is indeed generated now. Thanks!

**Comment by ronaldtse** [comment]
> But there are still these:
> 
> ```
> No label has been processed for ID change_history
> No label has been processed for ID AnnexD
> No label has been processed for ID annex_listings
> ```

@manuelfuenmayor could you help check what this is about? I'm going to close this issue for now. Maybe a new issue. Thanks!
