### ISSUE TITLE
Update module templates to correct missing sections

### ISSUE THREAD

**Issue by manuelfuenmayor** [metanorma/iso-10303-templates#24]
From https://github.com/metanorma/iso-10303-templates/issues/22

Due to new updates in iso-10303-srl, some sections are missing in module docs:

Part 1064:
```
No label has been processed for ID change_history
No label has been processed for ID AnnexD
No label has been processed for ID annex_listings
```

**Comment by ronaldtse** [comment]
@manuelfuenmayor any idea of what’s going on here?

**Comment by manuelfuenmayor** [comment]
@ronaldtse, the issue was a closing end of yaml2text block. It is fixed in https://github.com/metanorma/iso-10303-templates/pull/25/commits/0ed45e05b8217a8578c31fa3864abfce2784672a.

**Comment by manuelfuenmayor** [comment]
In addition, could you try to compile ISO 10303-1064 in this PR: https://github.com/metanorma/iso-10303-srl/pull/219?
I would like you to see something.

**Comment by manuelfuenmayor** [comment]
> I would like you to see something.

Don't worry, I still need to do some work. I'll let you know.

**Comment by ronaldtse** [comment]
> 10303-1064

Are you saying it takes a long time to build?

**Comment by manuelfuenmayor** [comment]
> Are you saying it takes a long time to build?

@ronaldtse yes, and the solution I propose is to create individual "schemas_all.yaml" files (maybe with a different name) for each document to contain only the needed schemas for that document in particular. I'm figuring out a script to do that.

**Comment by TRThurman** [comment]
@ronaldtse @manuelfuenmayor, That can be an expensive process. 
Note that the MIM is the superset of the ARM so no need to do both. 

I don't know enough about Expressir to know if it will help. We use Express engine to generate a concatenated file and then extract schema names from that. I know Ron has issues with Express engine...

**Comment by manuelfuenmayor** [comment]
> @ronaldtse, the issue was a closing end of yaml2text block. It is fixed in https://github.com/metanorma/iso-10303-templates/commit/0ed45e05b8217a8578c31fa3864abfce2784672a.

This issue was fixed weeks ago. Closing.
